[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The SCIL multimodale MRI"
authors = [{name = "SCIL", email = "Manon.edde@USherbrooke.ca"}]
dynamic = ["version", "description"]
